# Generated by Django 2.2.2 on 2019-06-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('gmc_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField()),
                ('NI_no', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HMRCstarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_statment', models.CharField(max_length=1, null=True)),
                ('student_loan9', models.BooleanField(null=True)),
                ('student_loan10', models.BooleanField(null=True)),
                ('student_loan11', models.BooleanField(null=True)),
                ('student_loanPlan', models.CharField(max_length=1, null=True)),
                ('postgraduate_loan13', models.BooleanField(null=True)),
                ('postgraduate_loan14', models.BooleanField(null=True)),
                ('postgraduate_loan15', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('cert_file', models.FileField(upload_to='certificates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=100)),
                ('second_line', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.Doctor')),
            ],
        ),
    ]
