# Generated by Django 2.2.2 on 2019-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_remove_doctor_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
