# Generated by Django 2.2.2 on 2019-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_auto_20190615_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_file',
            field=models.FileField(upload_to='certificates'),
        ),
    ]
